### ISSUE TITLE
Repository for publishing is not specified.

### ISSUE THREAD

**Issue by shivamka1** [lagom/lagom-samples#168]
This is regarding the [shopping-cart-scala](https://github.com/lagom/lagom-samples/tree/1.6.x/shopping-cart/shopping-cart-scala) app.

I get the following error when I try to publish the docker images to docker hub:
```
[error] java.lang.RuntimeException: Repository for publishing is not specified.
[error] 	at scala.sys.package$.error(package.scala:26)
[error] 	at sbt.Classpaths$.$anonfun$getPublishTo$1(Defaults.scala:2644)
[error] 	at scala.Option.getOrElse(Option.scala:121)
[error] 	at sbt.Classpaths$.getPublishTo(Defaults.scala:2644)
[error] 	at sbt.Classpaths$.$anonfun$ivyBaseSettings$48(Defaults.scala:2089)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
```

I pass docker username and respository as an argument to sbt like so:
```
sbt -Ddocker.username=codingkapoor -Ddocker.registry=index.docker.io
```

Images do get pushed but I still the error when I try to publish `docker:publish`.

Please suggest. TIA.

**Comment by octonato** [comment]
Have you followed this guide? 
https://developer.lightbend.com/guides/openshift-deployment/lagom/building-using-sbt.html

**Comment by shivamka1** [comment]
Yes. @renatocaval
