### ISSUE TITLE
Tests using withJdbc() fail to start up with timeout

### ISSUE THREAD

**Issue by ravredd** [lagom/lagom-samples#204]
When trying to test my own service utilizing   ServiceTest.Setup setup = defaultSetup().withJdbc();  startServer(setup);  - The services timeouts  on startup with bellow stack trace.  So I looked at the lagom-samples/shopping-cart/shopping-cart-java and cloned repo.  I executed mvn clean test and it also times out with the following.  I looked for an override or why it is failing but haven't found either.  Please advise.  Will also try to post on gitter as well.  Here is stack trace: 

java.util.concurrent.TimeoutException: Future timed out after [15 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.tryAwait0(Promise.scala:212)
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:104)
	at scala.concurrent.Await$.$anonfun$ready$1(package.scala:174)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:62)
	at scala.concurrent.Await$.ready(package.scala:124)
	at com.lightbend.lagom.internal.persistence.testkit.AwaitPersistenceInit$.awaitPersistenceInit(AwaitPersistenceInit.scala:55)
	at com.lightbend.lagom.javadsl.testkit.ServiceTest$.startServer(ServiceTest.scala:408)
	at com.lightbend.lagom.javadsl.testkit.ServiceTest.startServer(ServiceTest.scala)
	at com.example.shoppingcart.impl.ShoppingCartReportTest.beforeAll(ShoppingCartReportTest.java:44)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

**Comment by ravredd** [comment]
Appears it is hardcoded in testkit for 15 second wait time. But withJdbc doesn't start up in that time. https://github.com/lagom/lagom/blob/master/persistence/testkit/src/main/scala/com/lightbend/lagom/internal/persistence/testkit/AwaitPersistenceInit.scala line 55
